language: node_js
node_js:
  - '6'
  - '8'
  - '10'
  - '12'
  - '14'
jobs:
  fast_finish: true
  allow_failures:
    - node_js: 6
script:
  - npm run lint
  - npm run cover
after_script:
  - npm run publish-coverage
